### ISSUE TITLE
The release tarball on Hackage lacks a Setup.hs file

### ISSUE THREAD

**Issue by peti** [ncaq/haskell-import-graph#1]
Many build systems (like ours at openSUSE.org) rely on being able to run `runhaskell Setup.hs build` etc. to build a package, but unfortunate we cannot build yours this way because the `Setup.hs` file is missing. Would you mind releasing a minor version update that remedies this issue?

**Comment by ncaq** [comment]
Sorry, I miss there issues.
I do it now.

**Comment by ncaq** [comment]
I don't know to reason that need Setup.hs for `build-type:     Simple`.
However, I added.
